In [1]:
import torch
import torch.nn as nn
import numpy as np
import math
from torch.nn.parameter import Parameter

In [2]:
def make_mask(dim):
        matirx = np.ones((dim, dim))
        mask = torch.Tensor(np.tril(matirx))
        return mask==1
print(make_mask(5))

tensor([[ True, False, False, False, False],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])


In [16]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 3, 4)
tensor3 = torch.randn(10, 3, 4)
a = np.arange(9).astype('float').reshape(3,3)

tensor4 = torch.from_numpy(a)
print(tensor4)
m = nn.Softmax(dim=1)
X = m(tensor4)
print(X)
print(torch.bmm(torch.bmm(tensor1, tensor2.permute((0,2,1))), tensor3).size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]], dtype=torch.float64)
tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]], dtype=torch.float64)
torch.Size([10, 3, 4])


In [21]:

a = np.array([1.0,0.0,0.0,1.0]).reshape((2,2))
tensor4 = torch.from_numpy(a)
print(tensor4)
m = nn.Softmax(dim=1)
X = m(tensor4)
print(X)

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)
tensor([[0.7311, 0.2689],
        [0.2689, 0.7311]], dtype=torch.float64)


In [ ]:
nn.Transformer()